### ISSUE TITLE
Not working on latest version

### ISSUE THREAD

**Issue by ijjimem** [samuelgoldenbaum/elementor-responsive-image#1]
Image showing but not changing between devices

**Comment by samuelgoldenbaum** [comment]
If simply you resize the browser, the image may not change as the browser will see it has a file in cache . Load the page in mobile/desktop and view the response. I can confirm we have deployed in Elementor 3.5.0 Pro 3.5.2 yesterday and all OK. Let me know if that works for you.

**Comment by ijjimem** [comment]
Hey, i've checked and no.

`<img alt="" title="" loading="lazy" width="580" height="473" srcset="https://everyad.co.il/wp-content/uploads/2021/12/siudkol-logo.webp 800w, https://everyad.co.il/wp-content/uploads/2021/12/siudkol-logo.webp 800w, https://everyad.co.il/wp-content/uploads/2021/12/siudkol-logo-square.webp 580w" sizes="(min-width: 1025px) 400px, , (min-width: 768px) 400px, 290px" src="https://everyad.co.il/wp-content/uploads/2021/12/siudkol-logo-square.webp">`

**Comment by ijjimem** [comment]
Yes you are right, but the image stays as of Desktop version. Couldn't find a solution.

**Comment by ijjimem** [comment]
As it seems from tests it has to do with the min-width.

**Comment by jstormthakid** [comment]
Hey @samuelgoldenbaum, I created an account just to comment on this... I can confirm that this absolutely does not work on the latest version still... as @ijjimem mentioned, the image does show but stays as the desktop version and never changes. Can we get an updated fixed version of this?

**Comment by samuelgoldenbaum** [comment]
> Hey @samuelgoldenbaum, I created an account just to comment on this... I can confirm that this absolutely does not work on the latest version still... as @ijjimem mentioned, the image does show but stays as the desktop version and never changes. Can we get an updated fixed version of this?

Please be aware that chrome will not download a new version of the image if you simply resize a browser. This is a feature of that browser and by design–if it has an image in cache, it won't make a request for a new image. 

Feel free to test in Safari–look at the network panel in a site like [this](https://seachangeproject.com) while you resize the browser and you will see additional images being downloaded at the various breakpoints.
